name: Generate AWS Resource Governor Template

on:
  push:
    branches:
      - main
    paths:
      - 'lambda_function.py'
      - 'templates/aws-resource-governor.tpl.yaml'
      - 'policies/*.json'
  workflow_dispatch:

jobs:
  generate-template:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate CloudFormation template with embedded code and policies
        run: |          
          # Copy template to final file
          cp templates/aws-resource-governor.tpl.yaml aws-resource-governor.yaml
          
          # Embed Lambda function code
          echo "Embedding Lambda function code..."
          sed 's/^/          /' lambda_function.py > temp_indented.py
          sed -i '/# Python code here/r temp_indented.py' aws-resource-governor.yaml
                    
          echo "✅ Successfully generated aws-resource-governor.yaml"
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Commit and push changes
        run: |
          git add aws-resource-governor.yaml
          git commit -m "Auto-generate: Create aws-resource-governor.yaml from template"
          
          # Push to the main branch
          git push origin HEAD:main
      
      